# Generated by Django 3.1.5 on 2021-01-23 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dodatkowe_uslugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nazwa_dodatkowej_uslugi', models.CharField(max_length=25)),
                ('opis_uslugi', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Dodatkowa usluga',
                'verbose_name_plural': 'Dodatkowe uslugi',
            },
        ),
        migrations.CreateModel(
            name='Pobyt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zakwaterowania', models.DateField(default=datetime.date(2021, 1, 23), verbose_name='Data_zakwaterowania')),
                ('data_wykwaterowania', models.DateField(blank=True, verbose_name='Data_wykwaterowania')),
            ],
            options={
                'verbose_name': 'Pobyt',
                'verbose_name_plural': 'Pobyty',
            },
        ),
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nazwa_pokoju', models.CharField(max_length=20)),
                ('opis_pokoju', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Pokoj',
                'verbose_name_plural': 'Pokoje',
            },
        ),
        migrations.CreateModel(
            name='Usluga_spa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_jednostkowa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nazwa_uslugi', models.CharField(max_length=50)),
                ('opis_uslugi', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Usluga spa',
                'verbose_name_plural': 'Uslugi spa',
            },
        ),
        migrations.CreateModel(
            name='Rezerwacja_uslugi_spa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rezerwacji', models.DateField()),
                ('godzina_rezerwacji', models.TimeField()),
                ('ilosc_osob', models.IntegerField(max_length=1)),
                ('usluga_spa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Obsluga.usluga_spa')),
            ],
            options={
                'verbose_name': 'Rezerwacja uslugi spa',
                'verbose_name_plural': 'Rezerwacje uslug spa',
            },
        ),
        migrations.CreateModel(
            name='Rezerwacja_pokoju',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_calkowita', models.DecimalField(decimal_places=2, max_digits=20)),
                ('data_do', models.DateField()),
                ('data_od', models.DateField()),
                ('ilosc_dni', models.IntegerField(blank=True, max_length=3)),
                ('dodatkowe_uslugi', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Obsluga.dodatkowe_uslugi')),
                ('pobyt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Obsluga.pobyt')),
                ('pokoj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Obsluga.pokoj')),
            ],
            options={
                'verbose_name': 'Rezerwacja pokoju',
                'verbose_name_plural': 'Rezerwacje pokojow',
            },
        ),
    ]
