# Generated by Django 3.1.5 on 2021-01-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obsluga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokoj',
            name='standard',
            field=models.CharField(choices=[('PODSTAWOWY', 'podstawowy'), ('WYZSZY', 'wyzszy')], default='podstawowy', max_length=20),
        ),
    ]
