# Generated by Django 3.1.5 on 2021-01-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obsluga', '0002_pokoj_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokoj',
            name='czy_dostawka',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokoj',
            name='rodzaj',
            field=models.CharField(choices=[('jednoosobowy', 'jednoosobowy'), ('dwuosobowy', 'dwuosobowy'), ('trzyosobowy', 'trzyosobowy')], default='jednoosobowy', max_length=20),
        ),
        migrations.AlterField(
            model_name='pokoj',
            name='standard',
            field=models.CharField(choices=[('podstawowy', 'podstawowy'), ('wyzszy', 'wyzszy')], default='podstawowy', max_length=20),
        ),
    ]
