# Generated by Django 3.1.5 on 2021-01-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obsluga', '0004_auto_20210123_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokoj',
            name='Dostawka dla dziecka',
        ),
        migrations.AddField(
            model_name='pokoj',
            name='czy_dostawka',
            field=models.BooleanField(default=False, verbose_name='Dostawka dla dziecka'),
        ),
    ]
