# Generated by Django 3.1.5 on 2021-01-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Obsluga', '0005_auto_20210123_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokoj',
            name='czy_dostawka',
        ),
    ]
